version: "3"

services:
  db:
    platform: linux/x86_64
    build:
      context: ./Docker/db
      dockerfile: Dockerfile
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Abc1234
